[server]
# the host IP of the server
host = "0.0.0.0"

# the port the server is running on
port = 4000


# This is an example account, copy and paste this entire block to make more
# accounts.
#	username: The account's username
#	password: The account's password
#	access: An array of strings representing channel names that the account has
#		the ability to see and modify. The only special string supported is "*"
#		which is the equivalent of all channels within the system.
[[accounts]]
username = "example"
password = "change-this-password-because-it's-incredibly-insecure-since-it's-public"
access = ["*"]